version: '3.9'

services:
  mongo-server:
    image: mongo:latest
    container_name: mongodb-server
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: guybrush
      MONGO_INITDB_ROOT_PASSWORD: iwannabeapirate
    ports:
      - '27017:27017'
    networks:
      - mongodb_network
    volumes:
      - mongodb_data:/data/db
  mongo-client:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    depends_on:
      - mongo-server
    environment:
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_SERVER: mongo-server
    ports:
      - '8081:8081'
    networks:
      - mongodb_network
volumes:
  mongodb_data:
networks:
  mongodb_network:
